/*
 * OpenDeezer — native GNOME front-end (GTK4 + libadwaita).
 *
 * The entire engine (login, browse, Blowfish decrypt, MP3 decode, ALSA
 * playback) is the Go core compiled to a C static archive
 * (lib/libdeezercore.a) and linked in-process; this file is UI only.
 *
 * Layout:  AdwApplicationWindow > AdwNavigationSplitView
 *            sidebar  : Liked Songs + the user's playlists (GtkListBox)
 *            content  : a GtkColumnView track table + a now-playing bottom bar,
 *                       with a search entry in the header.
 *
 * Threading: every DZ* call that touches the network (DZInit, the *JSON browse
 * calls, DZPlay, DZFetch) BLOCKS, so it runs on a GTask worker thread and the
 * result is marshalled back to the main loop in the completion callback. Cheap
 * state reads (DZState/DZPositionMS/...) are polled directly from a 300 ms
 * g_timeout on the main thread.
 */

#include <adwaita.h>
#include <json-glib/json-glib.h>
#include <stdarg.h>

#include "libdeezercore.h" /* DZ* C API generated by `go build -buildmode=c-archive` */

/* Deezer "Electric Violet". */
#define ACCENT "#A238FF"

/* ---------------------------------------------------------------------------
 * DzTrack — a tiny GObject so the GListStore backing the column view can hold
 * rich track rows. Plain GObject (no widgets), so it is safe to build anywhere.
 * ------------------------------------------------------------------------- */

#define DZ_TYPE_TRACK (dz_track_get_type())
G_DECLARE_FINAL_TYPE(DzTrack, dz_track, DZ, TRACK, GObject)

struct _DzTrack {
  GObject parent_instance;
  char   *id;
  char   *name;
  char   *artist;  /* artistLine */
  char   *album;   /* albumName  */
  char   *artwork; /* artworkUrl */
  gint64  duration_ms;
};

G_DEFINE_FINAL_TYPE(DzTrack, dz_track, G_TYPE_OBJECT)

static void dz_track_finalize(GObject *o) {
  DzTrack *t = DZ_TRACK(o);
  g_free(t->id);
  g_free(t->name);
  g_free(t->artist);
  g_free(t->album);
  g_free(t->artwork);
  G_OBJECT_CLASS(dz_track_parent_class)->finalize(o);
}
static void dz_track_class_init(DzTrackClass *k) { G_OBJECT_CLASS(k)->finalize = dz_track_finalize; }
static void dz_track_init(DzTrack *t) { (void)t; }

static DzTrack *dz_track_new(const char *id, const char *name, const char *artist,
                             const char *album, const char *artwork, gint64 dur) {
  DzTrack *t = g_object_new(DZ_TYPE_TRACK, NULL);
  t->id = g_strdup(id ? id : "");
  t->name = g_strdup(name ? name : "");
  t->artist = g_strdup(artist ? artist : "");
  t->album = g_strdup(album ? album : "");
  t->artwork = g_strdup(artwork ? artwork : "");
  t->duration_ms = dur;
  return t;
}

/* ---------------------------------------------------------------------------
 * App — all the widgets + playback bookkeeping for the single window.
 * ------------------------------------------------------------------------- */

typedef struct {
  AdwApplication       *app;
  AdwApplicationWindow *win;
  AdwToastOverlay      *toast;
  AdwNavigationPage    *content_page; /* title reflects the current source */

  /* track table */
  GtkColumnView        *track_view;
  GListStore           *track_store; /* DzTrack* — also the play queue */
  GtkSingleSelection   *track_sel;

  /* sidebar */
  GtkListBox           *sidebar;

  /* now-playing bar */
  GtkButton            *play_btn, *prev_btn, *next_btn;
  GtkLabel             *np_title, *np_subtitle, *pos_label, *dur_label;
  GtkPicture           *np_cover;
  GtkScale             *seek, *volume;

  gboolean              seeking;       /* user is dragging the scrubber */
  int                   current_index; /* index into track_store, -1 if none */
  int                   last_finished; /* DZFinishedCount snapshot */
  guint                 cover_gen;     /* drops stale async cover fetches */

  /* persisted settings (~/.config/opendeezer/settings.ini) */
  int                   quality;       /* 0 Normal(128), 1 High(320), 2 HiFi(FLAC) */
  gboolean              background;    /* keep playing on window close */

  /* MPRIS — OS media controls over the session bus (GDBus) */
  GDBusConnection      *bus;           /* set in on_bus_acquired */
  GDBusNodeInfo        *mpris_node;    /* parsed introspection */
  guint                 bus_name_id;   /* g_bus_own_name id */
  guint                 mpris_root_id; /* registered MediaPlayer2 object */
  guint                 mpris_player_id; /* registered .Player object */
  char                 *mpris_status;  /* last published PlaybackStatus */

  gboolean              held;          /* g_application_hold is active */
} App;

static App *APP; /* single window — a global keeps GTask plumbing tidy */

/* sidebar row kinds */
enum { ROW_LIKED = 0, ROW_PLAYLIST = 1 };

/* browse kinds */
typedef enum { LOAD_FAVORITES, LOAD_PLAYLIST, LOAD_ALBUM, LOAD_SEARCH } LoadKind;

/* forward declarations */
static void play_index(App *a, int idx);
static void play_relative(App *a, int delta);
static void start_cover_fetch(App *a, const char *url);
static void load_async(App *a, LoadKind kind, const char *arg);
static void load_playlists_async(App *a);
static void toast(App *a, const char *msg);

/* settings */
static void settings_load(App *a);
static void settings_save(App *a);

/* MPRIS notifications (defined after the playback section) */
static void mpris_notify_track(App *a);
static void mpris_notify_status(App *a, const char *status);
static void mpris_notify_volume(App *a);
static void mpris_emit_seeked(App *a, gint64 pos_ms);
static void mpris_setup(App *a);

/* background window helpers */
static void show_window(App *a);

/* ---------------------------------------------------------------------------
 * small helpers
 * ------------------------------------------------------------------------- */

static void toast(App *a, const char *msg) {
  if (a && a->toast)
    adw_toast_overlay_add_toast(a->toast, adw_toast_new(msg));
}

G_GNUC_PRINTF(2, 3)
static void toastf(App *a, const char *fmt, ...) {
  va_list ap;
  va_start(ap, fmt);
  char *m = g_strdup_vprintf(fmt, ap);
  va_end(ap);
  toast(a, m);
  g_free(m);
}

static char *ms_to_text(gint64 ms) {
  if (ms < 0) ms = 0;
  gint64 s = ms / 1000;
  return g_strdup_printf("%lld:%02lld", (long long)(s / 60), (long long)(s % 60));
}

/* Read the ARL from $DEEZER_ARL, else ~/.config/opendeezer/arl.txt. Caller frees. */
static char *read_arl(void) {
  const char *env = g_getenv("DEEZER_ARL");
  if (env && *env)
    return g_strstrip(g_strdup(env));
  char *path = g_build_filename(g_get_user_config_dir(), "opendeezer", "arl.txt", NULL);
  char *contents = NULL;
  gboolean ok = g_file_get_contents(path, &contents, NULL, NULL);
  g_free(path);
  if (ok)
    return g_strstrip(contents); /* trims in place, returns same buffer */
  return NULL;
}

/* safe json-glib string accessor */
static char *jstr(JsonObject *o, const char *key) {
  if (o && json_object_has_member(o, key)) {
    JsonNode *n = json_object_get_member(o, key);
    if (JSON_NODE_HOLDS_VALUE(n)) {
      const char *s = json_node_get_string(n);
      return g_strdup(s ? s : "");
    }
  }
  return g_strdup("");
}
static gint64 jint(JsonObject *o, const char *key) {
  if (o && json_object_has_member(o, key)) {
    JsonNode *n = json_object_get_member(o, key);
    if (JSON_NODE_HOLDS_VALUE(n))
      return json_node_get_int(n);
  }
  return 0;
}

static DzTrack *dz_track_from_json(JsonObject *o) {
  char *id = jstr(o, "id"), *name = jstr(o, "name"), *artist = jstr(o, "artistLine"),
       *album = jstr(o, "albumName"), *art = jstr(o, "artworkUrl");
  DzTrack *t = dz_track_new(id, name, artist, album, art, jint(o, "durationMs"));
  g_free(id); g_free(name); g_free(artist); g_free(album); g_free(art);
  return t;
}

/* ---------------------------------------------------------------------------
 * column view factories
 * ------------------------------------------------------------------------- */

static void setup_label(GtkSignalListItemFactory *f, GtkListItem *item, gpointer end) {
  (void)f;
  GtkWidget *l = gtk_label_new("");
  gtk_label_set_xalign(GTK_LABEL(l), end ? 1.0 : 0.0);
  gtk_label_set_ellipsize(GTK_LABEL(l), PANGO_ELLIPSIZE_END);
  if (end) gtk_widget_add_css_class(l, "dim-label");
  gtk_list_item_set_child(item, l);
}

static void bind_title(GtkSignalListItemFactory *f, GtkListItem *item, gpointer u) {
  (void)f; (void)u;
  DzTrack *t = gtk_list_item_get_item(item);
  gtk_label_set_label(GTK_LABEL(gtk_list_item_get_child(item)), t->name);
}
static void bind_artist(GtkSignalListItemFactory *f, GtkListItem *item, gpointer u) {
  (void)f; (void)u;
  DzTrack *t = gtk_list_item_get_item(item);
  gtk_label_set_label(GTK_LABEL(gtk_list_item_get_child(item)), t->artist);
}
static void bind_album(GtkSignalListItemFactory *f, GtkListItem *item, gpointer u) {
  (void)f; (void)u;
  DzTrack *t = gtk_list_item_get_item(item);
  gtk_label_set_label(GTK_LABEL(gtk_list_item_get_child(item)), t->album);
}
static void bind_time(GtkSignalListItemFactory *f, GtkListItem *item, gpointer u) {
  (void)f; (void)u;
  DzTrack *t = gtk_list_item_get_item(item);
  char *s = ms_to_text(t->duration_ms);
  gtk_label_set_label(GTK_LABEL(gtk_list_item_get_child(item)), s);
  g_free(s);
}

static GtkColumnViewColumn *make_column(const char *title, gboolean expand, gboolean end,
                                        GCallback bind_cb) {
  GtkListItemFactory *f = gtk_signal_list_item_factory_new();
  g_signal_connect(f, "setup", G_CALLBACK(setup_label), GINT_TO_POINTER(end));
  g_signal_connect(f, "bind", bind_cb, NULL);
  GtkColumnViewColumn *col = gtk_column_view_column_new(title, f);
  gtk_column_view_column_set_expand(col, expand);
  return col;
}

/* play the track the user activated (Enter / double-click) */
static void on_row_activate(GtkColumnView *cv, guint pos, gpointer data) {
  (void)cv;
  play_index((App *)data, (int)pos);
}

/* ---------------------------------------------------------------------------
 * browse: load a track list on a worker thread, populate on the main thread
 * ------------------------------------------------------------------------- */

typedef struct { LoadKind kind; char *arg; } LoadCtx;
static void load_ctx_free(gpointer p) { LoadCtx *c = p; g_free(c->arg); g_free(c); }

static void load_worker(GTask *task, gpointer src, gpointer data, GCancellable *c) {
  (void)src; (void)c;
  LoadCtx *ctx = data;
  char *j = NULL;
  switch (ctx->kind) {
    case LOAD_FAVORITES: j = DZFavoritesJSON(); break;
    case LOAD_PLAYLIST:  j = DZPlaylistTracksJSON(ctx->arg); break;
    case LOAD_ALBUM:     j = DZAlbumTracksJSON(ctx->arg); break;
    case LOAD_SEARCH:    j = DZSearchJSON(ctx->arg); break;
  }
  char *dup = g_strdup(j ? j : "{}");
  if (j) DZFree(j);
  g_task_return_pointer(task, dup, g_free);
}

/* fills the column store from a {"tracks":[...]} (or search) JSON payload */
static void populate_tracks(App *a, const char *json) {
  g_list_store_remove_all(a->track_store);
  a->current_index = -1;
  if (!json) return;

  JsonParser *p = json_parser_new();
  GError *e = NULL;
  if (!json_parser_load_from_data(p, json, -1, &e)) {
    toastf(a, "Couldn't parse response: %s", e->message);
    g_clear_error(&e);
    g_object_unref(p);
    return;
  }
  JsonNode *root = json_parser_get_root(p);
  if (root && JSON_NODE_HOLDS_OBJECT(root)) {
    JsonObject *o = json_node_get_object(root);
    if (json_object_has_member(o, "error")) {
      char *msg = jstr(o, "error");
      if (*msg) toastf(a, "Deezer: %s", msg);
      g_free(msg);
    }
    if (json_object_has_member(o, "tracks")) {
      JsonArray *arr = json_object_get_array_member(o, "tracks");
      guint n = json_array_get_length(arr);
      for (guint i = 0; i < n; i++) {
        DzTrack *t = dz_track_from_json(json_array_get_object_element(arr, i));
        g_list_store_append(a->track_store, t);
        g_object_unref(t);
      }
      toastf(a, n == 1 ? "%u track" : "%u tracks", n);
    }
  }
  g_object_unref(p);
}

static void load_done(GObject *src, GAsyncResult *res, gpointer data) {
  (void)src; (void)data;
  char *json = g_task_propagate_pointer(G_TASK(res), NULL);
  populate_tracks(APP, json);
  g_free(json);
}

static void load_async(App *a, LoadKind kind, const char *arg) {
  LoadCtx *c = g_new0(LoadCtx, 1);
  c->kind = kind;
  c->arg = g_strdup(arg ? arg : "");
  GTask *t = g_task_new(NULL, NULL, load_done, NULL);
  g_task_set_task_data(t, c, load_ctx_free);
  g_task_run_in_thread(t, load_worker);
  g_object_unref(t);
}

/* ---------------------------------------------------------------------------
 * sidebar: the playlists list is fetched once after login
 * ------------------------------------------------------------------------- */

static GtkWidget *make_side_row(const char *title, const char *subtitle, const char *icon,
                                int kind, const char *id) {
  GtkWidget *row = adw_action_row_new();
  adw_preferences_row_set_title(ADW_PREFERENCES_ROW(row), title);
  if (subtitle && *subtitle)
    adw_action_row_set_subtitle(ADW_ACTION_ROW(row), subtitle);
  if (icon)
    adw_action_row_add_prefix(ADW_ACTION_ROW(row), gtk_image_new_from_icon_name(icon));
  g_object_set_data(G_OBJECT(row), "kind", GINT_TO_POINTER(kind));
  g_object_set_data_full(G_OBJECT(row), "id", g_strdup(id ? id : ""), g_free);
  g_object_set_data_full(G_OBJECT(row), "title", g_strdup(title), g_free);
  return row;
}

static void on_sidebar_selected(GtkListBox *box, GtkListBoxRow *row, gpointer data) {
  (void)box;
  App *a = data;
  if (!row) return;
  int kind = GPOINTER_TO_INT(g_object_get_data(G_OBJECT(row), "kind"));
  const char *id = g_object_get_data(G_OBJECT(row), "id");
  const char *title = g_object_get_data(G_OBJECT(row), "title");
  adw_navigation_page_set_title(a->content_page, title ? title : "");
  if (kind == ROW_PLAYLIST)
    load_async(a, LOAD_PLAYLIST, id);
  else
    load_async(a, LOAD_FAVORITES, NULL);
}

static void playlists_worker(GTask *task, gpointer src, gpointer data, GCancellable *c) {
  (void)src; (void)data; (void)c;
  char *j = DZPlaylistsJSON();
  char *dup = g_strdup(j ? j : "{}");
  if (j) DZFree(j);
  g_task_return_pointer(task, dup, g_free);
}

static void playlists_done(GObject *src, GAsyncResult *res, gpointer data) {
  (void)src; (void)data;
  char *json = g_task_propagate_pointer(G_TASK(res), NULL);
  if (!json) return;
  JsonParser *p = json_parser_new();
  if (json_parser_load_from_data(p, json, -1, NULL)) {
    JsonNode *root = json_parser_get_root(p);
    if (root && JSON_NODE_HOLDS_OBJECT(root)) {
      JsonObject *o = json_node_get_object(root);
      if (json_object_has_member(o, "playlists")) {
        JsonArray *arr = json_object_get_array_member(o, "playlists");
        for (guint i = 0; i < json_array_get_length(arr); i++) {
          JsonObject *pl = json_array_get_object_element(arr, i);
          char *name = jstr(pl, "name"), *owner = jstr(pl, "owner"), *id = jstr(pl, "id");
          char *sub = g_strdup_printf("%s · %lld tracks", owner, (long long)jint(pl, "trackCount"));
          gtk_list_box_append(APP->sidebar,
              make_side_row(name, sub, "view-list-symbolic", ROW_PLAYLIST, id));
          g_free(name); g_free(owner); g_free(id); g_free(sub);
        }
      }
    }
  }
  g_object_unref(p);
  g_free(json);
}

static void load_playlists_async(App *a) {
  (void)a;
  GTask *t = g_task_new(NULL, NULL, playlists_done, NULL);
  g_task_run_in_thread(t, playlists_worker);
  g_object_unref(t);
}

/* ---------------------------------------------------------------------------
 * playback
 * ------------------------------------------------------------------------- */

typedef struct { char *id; gint64 dur; } PlayCtx;
static void play_ctx_free(gpointer p) { PlayCtx *c = p; g_free(c->id); g_free(c); }

static void play_worker(GTask *task, gpointer src, gpointer data, GCancellable *c) {
  (void)src; (void)c;
  PlayCtx *p = data;
  int ok = DZPlay(p->id, p->dur); /* network: prepare stream + decode + play */
  g_task_return_boolean(task, ok == 1);
}
static void play_done(GObject *src, GAsyncResult *res, gpointer data) {
  (void)src; (void)data;
  gboolean ok = g_task_propagate_boolean(G_TASK(res), NULL);
  /* resync so the natural-finish counter doesn't trigger a spurious skip */
  APP->last_finished = DZFinishedCount();
  if (!ok) toast(APP, "Couldn't play that track");
}

static void play_index(App *a, int idx) {
  guint n = g_list_model_get_n_items(G_LIST_MODEL(a->track_store));
  if (idx < 0 || (guint)idx >= n) return;
  DzTrack *t = g_list_model_get_item(G_LIST_MODEL(a->track_store), idx); /* owns ref */
  a->current_index = idx;

  /* immediate UI feedback */
  gtk_label_set_label(a->np_title, t->name);
  gtk_label_set_label(a->np_subtitle, t->artist);
  gtk_range_set_range(GTK_RANGE(a->seek), 0, t->duration_ms > 0 ? (double)t->duration_ms : 1.0);
  gtk_range_set_value(GTK_RANGE(a->seek), 0);
  gtk_single_selection_set_selected(a->track_sel, idx);
  start_cover_fetch(a, t->artwork);

  /* push the new track to the OS media controls immediately (metadata is
   * already known; the Playing/Paused status follows from the poll). */
  mpris_notify_track(a);
  mpris_emit_seeked(a, 0);

  /* blocking play happens off the main loop */
  PlayCtx *ctx = g_new0(PlayCtx, 1);
  ctx->id = g_strdup(t->id);
  ctx->dur = t->duration_ms;
  GTask *task = g_task_new(NULL, NULL, play_done, NULL);
  g_task_set_task_data(task, ctx, play_ctx_free);
  g_task_run_in_thread(task, play_worker);
  g_object_unref(task);

  g_object_unref(t);
}

static void play_relative(App *a, int delta) {
  int base = a->current_index < 0 ? (delta > 0 ? -1 : 0) : a->current_index;
  play_index(a, base + delta);
}

static void on_play_clicked(GtkButton *b, gpointer data) {
  (void)b;
  App *a = data;
  if (a->current_index < 0)
    play_relative(a, 1); /* nothing playing yet: start the first row */
  else
    DZTogglePause();
}
static void on_prev_clicked(GtkButton *b, gpointer data) { (void)b; play_relative(data, -1); }
static void on_next_clicked(GtkButton *b, gpointer data) { (void)b; play_relative(data, 1); }

/* ---------------------------------------------------------------------------
 * settings: a tiny GKeyFile alongside arl.txt (~/.config/opendeezer/settings.ini)
 * ------------------------------------------------------------------------- */

static char *settings_path(void) {
  return g_build_filename(g_get_user_config_dir(), "opendeezer", "settings.ini", NULL);
}

static void settings_load(App *a) {
  /* sensible defaults: High quality, keep playing in background */
  a->quality = 1;
  a->background = TRUE;

  GKeyFile *kf = g_key_file_new();
  char *path = settings_path();
  if (g_key_file_load_from_file(kf, path, G_KEY_FILE_NONE, NULL)) {
    if (g_key_file_has_key(kf, "audio", "quality_level", NULL)) {
      a->quality = g_key_file_get_integer(kf, "audio", "quality_level", NULL);
      if (a->quality < 0) a->quality = 0;
      if (a->quality > 2) a->quality = 2;
    }
    if (g_key_file_has_key(kf, "general", "background", NULL))
      a->background = g_key_file_get_boolean(kf, "general", "background", NULL);
  }
  g_free(path);
  g_key_file_free(kf);
}

static void settings_save(App *a) {
  GKeyFile *kf = g_key_file_new();
  g_key_file_set_integer(kf, "audio", "quality_level", a->quality);
  g_key_file_set_boolean(kf, "general", "background", a->background);

  char *path = settings_path();
  char *dir = g_path_get_dirname(path);
  g_mkdir_with_parents(dir, 0700);
  g_key_file_save_to_file(kf, path, NULL); /* best effort */
  g_free(dir);
  g_free(path);
  g_key_file_free(kf);
}

static void on_quality_selected(GObject *row, GParamSpec *ps, gpointer data) {
  (void)ps;
  App *a = data;
  a->quality = (int)adw_combo_row_get_selected(ADW_COMBO_ROW(row));
  DZSetQuality(a->quality);
  settings_save(a);
  const char *names[] = {"Normal (MP3 128)", "High (MP3 320)", "HiFi (FLAC)"};
  toastf(a, "Audio quality: %s", names[a->quality < 0 ? 0 : (a->quality > 2 ? 2 : a->quality)]);
}

static void on_background_toggled(GObject *row, GParamSpec *ps, gpointer data) {
  (void)ps;
  App *a = data;
  a->background = adw_switch_row_get_active(ADW_SWITCH_ROW(row));
  settings_save(a);
}

static void on_settings(GSimpleAction *action, GVariant *param, gpointer data) {
  (void)action; (void)param; (void)data;
  App *a = APP;

  AdwPreferencesPage *page = ADW_PREFERENCES_PAGE(adw_preferences_page_new());
  adw_preferences_page_set_title(page, "Settings");
  adw_preferences_page_set_icon_name(page, "preferences-system-symbolic");

  /* ---- Audio ---- */
  AdwPreferencesGroup *audio = ADW_PREFERENCES_GROUP(adw_preferences_group_new());
  adw_preferences_group_set_title(audio, "Audio");

  const char *const qlabels[] = {"Normal — MP3 128 kbps",
                                 "High — MP3 320 kbps",
                                 "HiFi — FLAC lossless", NULL};
  GtkWidget *quality = adw_combo_row_new();
  adw_preferences_row_set_title(ADW_PREFERENCES_ROW(quality), "Streaming quality");
  adw_combo_row_set_model(ADW_COMBO_ROW(quality),
                          G_LIST_MODEL(gtk_string_list_new(qlabels)));
  adw_combo_row_set_selected(ADW_COMBO_ROW(quality), (guint)a->quality);
  g_signal_connect(quality, "notify::selected", G_CALLBACK(on_quality_selected), a);
  adw_preferences_group_add(audio, quality);
  adw_preferences_page_add(page, audio);

  /* ---- Behaviour ---- */
  AdwPreferencesGroup *behave = ADW_PREFERENCES_GROUP(adw_preferences_group_new());
  adw_preferences_group_set_title(behave, "Behaviour");

  GtkWidget *bg = adw_switch_row_new();
  adw_preferences_row_set_title(ADW_PREFERENCES_ROW(bg), "Keep playing in background");
  adw_action_row_set_subtitle(ADW_ACTION_ROW(bg),
                              "When the window is closed, keep playing and stay in the "
                              "system media controls instead of quitting");
  adw_switch_row_set_active(ADW_SWITCH_ROW(bg), a->background);
  g_signal_connect(bg, "notify::active", G_CALLBACK(on_background_toggled), a);
  adw_preferences_group_add(behave, bg);
  adw_preferences_page_add(page, behave);

#if ADW_CHECK_VERSION(1, 5, 0)
  AdwPreferencesDialog *dlg = ADW_PREFERENCES_DIALOG(adw_preferences_dialog_new());
  adw_preferences_dialog_add(dlg, page);
  adw_dialog_present(ADW_DIALOG(dlg), GTK_WIDGET(a->win));
#else
  GtkWidget *win = adw_preferences_window_new();
  adw_preferences_window_add(ADW_PREFERENCES_WINDOW(win), page);
  gtk_window_set_transient_for(GTK_WINDOW(win), GTK_WINDOW(a->win));
  gtk_window_set_modal(GTK_WINDOW(win), TRUE);
  gtk_window_present(GTK_WINDOW(win));
#endif
}

/* ---------------------------------------------------------------------------
 * MPRIS: org.mpris.MediaPlayer2(.Player) on the session bus via GDBus, so the
 * GNOME media overlay / lock screen / media keys can see and drive playback.
 * Both interfaces live on /org/mpris/MediaPlayer2; methods reuse the existing
 * transport handlers, and PropertiesChanged/Seeked are emitted from the poll
 * and on every track change. No new deps — GDBus ships in gio.
 * ------------------------------------------------------------------------- */

#define MPRIS_BUS_NAME   "org.mpris.MediaPlayer2.opendeezer"
#define MPRIS_OBJ_PATH   "/org/mpris/MediaPlayer2"
#define MPRIS_PLAYER_IFC "org.mpris.MediaPlayer2.Player"

static const char MPRIS_XML[] =
    "<node>"
    "  <interface name='org.mpris.MediaPlayer2'>"
    "    <method name='Raise'/>"
    "    <method name='Quit'/>"
    "    <property name='CanQuit' type='b' access='read'/>"
    "    <property name='CanRaise' type='b' access='read'/>"
    "    <property name='HasTrackList' type='b' access='read'/>"
    "    <property name='Identity' type='s' access='read'/>"
    "    <property name='DesktopEntry' type='s' access='read'/>"
    "    <property name='SupportedUriSchemes' type='as' access='read'/>"
    "    <property name='SupportedMimeTypes' type='as' access='read'/>"
    "  </interface>"
    "  <interface name='org.mpris.MediaPlayer2.Player'>"
    "    <method name='Next'/>"
    "    <method name='Previous'/>"
    "    <method name='Pause'/>"
    "    <method name='PlayPause'/>"
    "    <method name='Stop'/>"
    "    <method name='Play'/>"
    "    <method name='Seek'><arg name='Offset' type='x' direction='in'/></method>"
    "    <method name='SetPosition'>"
    "      <arg name='TrackId' type='o' direction='in'/>"
    "      <arg name='Position' type='x' direction='in'/>"
    "    </method>"
    "    <method name='OpenUri'><arg name='Uri' type='s' direction='in'/></method>"
    "    <signal name='Seeked'><arg name='Position' type='x'/></signal>"
    "    <property name='PlaybackStatus' type='s' access='read'/>"
    "    <property name='Rate' type='d' access='readwrite'/>"
    "    <property name='Metadata' type='a{sv}' access='read'/>"
    "    <property name='Volume' type='d' access='readwrite'/>"
    "    <property name='Position' type='x' access='read'/>"
    "    <property name='MinimumRate' type='d' access='read'/>"
    "    <property name='MaximumRate' type='d' access='read'/>"
    "    <property name='CanGoNext' type='b' access='read'/>"
    "    <property name='CanGoPrevious' type='b' access='read'/>"
    "    <property name='CanPlay' type='b' access='read'/>"
    "    <property name='CanPause' type='b' access='read'/>"
    "    <property name='CanSeek' type='b' access='read'/>"
    "    <property name='CanControl' type='b' access='read'/>"
    "  </interface>"
    "</node>";

static const char *mpris_status_str(int state) {
  if (state == 2) return "Playing";
  if (state == 3) return "Paused";
  return "Stopped";
}

/* the currently-selected DzTrack, or NULL — caller owns the returned ref */
static DzTrack *mpris_current_track(App *a) {
  if (a->current_index < 0) return NULL;
  guint n = g_list_model_get_n_items(G_LIST_MODEL(a->track_store));
  if ((guint)a->current_index >= n) return NULL;
  return g_list_model_get_item(G_LIST_MODEL(a->track_store), a->current_index);
}

/* build the a{sv} Metadata dict for the current track (floating ref) */
static GVariant *mpris_metadata(App *a) {
  GVariantBuilder b;
  g_variant_builder_init(&b, G_VARIANT_TYPE("a{sv}"));
  DzTrack *t = mpris_current_track(a);
  if (t) {
    /* object paths only allow [A-Za-z0-9_]; Deezer ids are digits but sanitise
     * anyway so a stray char can never produce an invalid path. */
    char *path = g_strdup_printf("/org/mpris/MediaPlayer2/opendeezer/track/%s",
                                 (t->id && *t->id) ? t->id : "0");
    for (char *p = path + 1; *p; p++)
      if (!(g_ascii_isalnum(*p) || *p == '_' || *p == '/')) *p = '_';
    g_variant_builder_add(&b, "{sv}", "mpris:trackid", g_variant_new_object_path(path));
    g_free(path);

    g_variant_builder_add(&b, "{sv}", "mpris:length",
                          g_variant_new_int64(t->duration_ms * 1000)); /* µs */
    g_variant_builder_add(&b, "{sv}", "xesam:title", g_variant_new_string(t->name));
    const char *artists[] = {t->artist, NULL};
    g_variant_builder_add(&b, "{sv}", "xesam:artist", g_variant_new_strv(artists, -1));
    g_variant_builder_add(&b, "{sv}", "xesam:album", g_variant_new_string(t->album));
    if (t->artwork && *t->artwork)
      g_variant_builder_add(&b, "{sv}", "mpris:artUrl", g_variant_new_string(t->artwork));
    g_object_unref(t);
  } else {
    g_variant_builder_add(&b, "{sv}", "mpris:trackid",
        g_variant_new_object_path("/org/mpris/MediaPlayer2/opendeezer/track/none"));
  }
  return g_variant_builder_end(&b);
}

static GVariant *mpris_get_prop(GDBusConnection *c, const char *sender, const char *path,
                                const char *iface, const char *prop, GError **err,
                                gpointer u) {
  (void)c; (void)sender; (void)path; (void)err;
  App *a = u;
  if (g_strcmp0(iface, "org.mpris.MediaPlayer2") == 0) {
    if (!g_strcmp0(prop, "Identity"))     return g_variant_new_string("OpenDeezer");
    if (!g_strcmp0(prop, "DesktopEntry")) return g_variant_new_string("org.opendeezer.OpenDeezer");
    if (!g_strcmp0(prop, "CanQuit"))      return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "CanRaise"))     return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "HasTrackList")) return g_variant_new_boolean(FALSE);
    if (!g_strcmp0(prop, "SupportedUriSchemes") || !g_strcmp0(prop, "SupportedMimeTypes")) {
      const char *empty[] = {NULL};
      return g_variant_new_strv(empty, 0);
    }
  } else if (g_strcmp0(iface, MPRIS_PLAYER_IFC) == 0) {
    if (!g_strcmp0(prop, "PlaybackStatus")) return g_variant_new_string(mpris_status_str(DZState()));
    if (!g_strcmp0(prop, "Metadata"))       return mpris_metadata(a);
    if (!g_strcmp0(prop, "Position"))       return g_variant_new_int64(DZPositionMS() * 1000);
    if (!g_strcmp0(prop, "Rate"))           return g_variant_new_double(1.0);
    if (!g_strcmp0(prop, "MinimumRate"))    return g_variant_new_double(1.0);
    if (!g_strcmp0(prop, "MaximumRate"))    return g_variant_new_double(1.0);
    if (!g_strcmp0(prop, "Volume"))         return g_variant_new_double(DZVolume());
    if (!g_strcmp0(prop, "CanGoNext"))      return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "CanGoPrevious"))  return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "CanPlay"))        return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "CanPause"))       return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "CanSeek"))        return g_variant_new_boolean(TRUE);
    if (!g_strcmp0(prop, "CanControl"))     return g_variant_new_boolean(TRUE);
  }
  return NULL;
}

static gboolean mpris_set_prop(GDBusConnection *c, const char *sender, const char *path,
                               const char *iface, const char *prop, GVariant *value,
                               GError **err, gpointer u) {
  (void)c; (void)sender; (void)path; (void)iface; (void)err;
  App *a = u;
  if (!g_strcmp0(prop, "Volume")) {
    double v = g_variant_get_double(value);
    if (v < 0) v = 0; if (v > 1) v = 1;
    DZSetVolume(v);
    if (a->volume) gtk_range_set_value(GTK_RANGE(a->volume), v); /* keeps UI in sync */
    mpris_notify_volume(a);
    return TRUE;
  }
  if (!g_strcmp0(prop, "Rate")) return TRUE; /* fixed at 1.0, accept silently */
  return FALSE;
}

static void mpris_root_method(GDBusConnection *c, const char *sender, const char *path,
                              const char *iface, const char *method, GVariant *params,
                              GDBusMethodInvocation *inv, gpointer u) {
  (void)c; (void)sender; (void)path; (void)iface; (void)params;
  App *a = u;
  if (!g_strcmp0(method, "Raise"))
    show_window(a);
  else if (!g_strcmp0(method, "Quit"))
    g_application_quit(G_APPLICATION(a->app));
  g_dbus_method_invocation_return_value(inv, NULL);
}

static void mpris_player_method(GDBusConnection *c, const char *sender, const char *path,
                                const char *iface, const char *method, GVariant *params,
                                GDBusMethodInvocation *inv, gpointer u) {
  (void)c; (void)sender; (void)path; (void)iface;
  App *a = u;
  if (!g_strcmp0(method, "PlayPause")) {
    if (a->current_index < 0) play_relative(a, 1); else DZTogglePause();
  } else if (!g_strcmp0(method, "Play")) {
    int st = DZState();
    if (st == 3) DZResume();
    else if (st != 2) { if (a->current_index < 0) play_relative(a, 1); else DZResume(); }
  } else if (!g_strcmp0(method, "Pause")) {
    DZPause();
  } else if (!g_strcmp0(method, "Stop")) {
    DZStop();
  } else if (!g_strcmp0(method, "Next")) {
    play_relative(a, 1);
  } else if (!g_strcmp0(method, "Previous")) {
    play_relative(a, -1);
  } else if (!g_strcmp0(method, "Seek")) {
    gint64 off = 0;
    g_variant_get(params, "(x)", &off);           /* µs, may be negative */
    gint64 np = DZPositionMS() + off / 1000;       /* engine works in ms */
    if (np < 0) np = 0;
    DZSeek((long long)np);
    mpris_emit_seeked(a, np);
  } else if (!g_strcmp0(method, "SetPosition")) {
    const char *tid = NULL; gint64 pos = 0;
    g_variant_get(params, "(&ox)", &tid, &pos);
    gint64 np = pos / 1000;
    if (np < 0) np = 0;
    DZSeek((long long)np);
    mpris_emit_seeked(a, np);
  }
  /* OpenUri is unsupported — fall through to an empty reply */
  g_dbus_method_invocation_return_value(inv, NULL);
}

/* register_object copies the vtable, but keep these static to be safe */
static const GDBusInterfaceVTable mpris_root_vtable = {
    mpris_root_method, mpris_get_prop, mpris_set_prop, {0}};
static const GDBusInterfaceVTable mpris_player_vtable = {
    mpris_player_method, mpris_get_prop, mpris_set_prop, {0}};

/* emit PropertiesChanged on .Player for the {Metadata, PlaybackStatus} pair */
static void mpris_notify_track(App *a) {
  if (!a->bus) return;
  GVariantBuilder b;
  g_variant_builder_init(&b, G_VARIANT_TYPE("a{sv}"));
  g_variant_builder_add(&b, "{sv}", "Metadata", mpris_metadata(a));
  g_variant_builder_add(&b, "{sv}", "PlaybackStatus",
                        g_variant_new_string(mpris_status_str(DZState())));
  g_variant_builder_add(&b, "{sv}", "CanGoNext", g_variant_new_boolean(TRUE));
  g_variant_builder_add(&b, "{sv}", "CanGoPrevious", g_variant_new_boolean(TRUE));
  g_dbus_connection_emit_signal(
      a->bus, NULL, MPRIS_OBJ_PATH, "org.freedesktop.DBus.Properties", "PropertiesChanged",
      g_variant_new("(sa{sv}as)", MPRIS_PLAYER_IFC, &b, NULL), NULL);
}

static void mpris_notify_status(App *a, const char *status) {
  if (!a->bus) return;
  GVariantBuilder b;
  g_variant_builder_init(&b, G_VARIANT_TYPE("a{sv}"));
  g_variant_builder_add(&b, "{sv}", "PlaybackStatus", g_variant_new_string(status));
  g_dbus_connection_emit_signal(
      a->bus, NULL, MPRIS_OBJ_PATH, "org.freedesktop.DBus.Properties", "PropertiesChanged",
      g_variant_new("(sa{sv}as)", MPRIS_PLAYER_IFC, &b, NULL), NULL);
}

static void mpris_notify_volume(App *a) {
  if (!a->bus) return;
  GVariantBuilder b;
  g_variant_builder_init(&b, G_VARIANT_TYPE("a{sv}"));
  g_variant_builder_add(&b, "{sv}", "Volume", g_variant_new_double(DZVolume()));
  g_dbus_connection_emit_signal(
      a->bus, NULL, MPRIS_OBJ_PATH, "org.freedesktop.DBus.Properties", "PropertiesChanged",
      g_variant_new("(sa{sv}as)", MPRIS_PLAYER_IFC, &b, NULL), NULL);
}

static void mpris_emit_seeked(App *a, gint64 pos_ms) {
  if (!a->bus) return;
  g_dbus_connection_emit_signal(a->bus, NULL, MPRIS_OBJ_PATH, MPRIS_PLAYER_IFC, "Seeked",
                                g_variant_new("(x)", pos_ms * 1000), NULL);
}

static void on_bus_acquired(GDBusConnection *c, const char *name, gpointer u) {
  (void)name;
  App *a = u;
  a->bus = c;
  if (!a->mpris_node) return;
  a->mpris_root_id = g_dbus_connection_register_object(
      c, MPRIS_OBJ_PATH, a->mpris_node->interfaces[0], &mpris_root_vtable, a, NULL, NULL);
  a->mpris_player_id = g_dbus_connection_register_object(
      c, MPRIS_OBJ_PATH, a->mpris_node->interfaces[1], &mpris_player_vtable, a, NULL, NULL);
}

static void mpris_setup(App *a) {
  GError *e = NULL;
  a->mpris_node = g_dbus_node_info_new_for_xml(MPRIS_XML, &e);
  if (!a->mpris_node) {
    g_warning("MPRIS introspection failed: %s", e ? e->message : "?");
    g_clear_error(&e);
    return;
  }
  a->bus_name_id = g_bus_own_name(
      G_BUS_TYPE_SESSION, MPRIS_BUS_NAME, G_BUS_NAME_OWNER_FLAGS_ALLOW_REPLACEMENT,
      on_bus_acquired, NULL, NULL, a, NULL);
}

/* ---------------------------------------------------------------------------
 * background: GNOME discourages tray icons, so when "keep playing in
 * background" is on we hide the window and hold the GApplication alive; the
 * MPRIS controls (and relaunching / Raise) bring it back.
 * ------------------------------------------------------------------------- */

static void show_window(App *a) {
  if (!a->win) return;
  gtk_widget_set_visible(GTK_WIDGET(a->win), TRUE);
  gtk_window_present(GTK_WINDOW(a->win));
  if (a->held) {
    g_application_release(G_APPLICATION(a->app));
    a->held = FALSE;
  }
}

static gboolean on_window_close(GtkWindow *win, gpointer data) {
  App *a = data;
  if (!a->background)
    return FALSE; /* honour the setting: let the window (and app) close */

  /* keep the engine + main loop alive, hide the window */
  if (!a->held) {
    g_application_hold(G_APPLICATION(a->app));
    a->held = TRUE;
  }
  gtk_widget_set_visible(GTK_WIDGET(win), FALSE);

  GNotification *n = g_notification_new("OpenDeezer");
  g_notification_set_body(
      n, "Still playing in the background. Use the media controls or relaunch to reopen.");
  g_application_send_notification(G_APPLICATION(a->app), "opendeezer-background", n);
  g_object_unref(n);

  return TRUE; /* stop the default destroy */
}

/* ---------------------------------------------------------------------------
 * async cover art: DZFetch on a worker, decode to a GdkTexture, set on main
 * ------------------------------------------------------------------------- */

typedef struct { char *url; guint gen; } CoverCtx;
static void cover_ctx_free(gpointer p) { CoverCtx *c = p; g_free(c->url); g_free(c); }

static void cover_worker(GTask *task, gpointer src, gpointer data, GCancellable *c) {
  (void)src; (void)c;
  CoverCtx *ctx = data;
  int len = 0;
  unsigned char *buf = DZFetch(ctx->url, &len);
  GdkTexture *tex = NULL;
  if (buf && len > 0) {
    /* GdkPixbufLoader sniffs JPEG/PNG and is safe to run off the main thread. */
    GdkPixbufLoader *loader = gdk_pixbuf_loader_new();
    if (gdk_pixbuf_loader_write(loader, buf, len, NULL) &&
        gdk_pixbuf_loader_close(loader, NULL)) {
      GdkPixbuf *pix = gdk_pixbuf_loader_get_pixbuf(loader); /* borrowed */
      if (pix) {
        g_object_ref(pix);
        tex = gdk_texture_new_for_pixbuf(pix);
        g_object_unref(pix);
      }
    }
    g_object_unref(loader);
  }
  if (buf) DZFreeBytes(buf);
  g_task_return_pointer(task, tex, g_object_unref);
}

static void cover_done(GObject *src, GAsyncResult *res, gpointer data) {
  (void)src; (void)data;
  CoverCtx *ctx = g_task_get_task_data(G_TASK(res));
  GdkTexture *tex = g_task_propagate_pointer(G_TASK(res), NULL);
  if (tex && ctx->gen == APP->cover_gen)
    gtk_picture_set_paintable(APP->np_cover, GDK_PAINTABLE(tex)); /* refs */
  if (tex) g_object_unref(tex);
}

static void start_cover_fetch(App *a, const char *url) {
  a->cover_gen++; /* invalidate any in-flight fetch for the previous track */
  if (!url || !*url) {
    gtk_picture_set_paintable(a->np_cover, NULL);
    return;
  }
  CoverCtx *c = g_new0(CoverCtx, 1);
  c->url = g_strdup(url);
  c->gen = a->cover_gen;
  GTask *t = g_task_new(NULL, NULL, cover_done, NULL);
  g_task_set_task_data(t, c, cover_ctx_free);
  g_task_run_in_thread(t, cover_worker);
  g_object_unref(t);
}

/* ---------------------------------------------------------------------------
 * scrubber: a "seeking" flag stops the poll loop from fighting the drag
 * ------------------------------------------------------------------------- */

static void on_seek_pressed(GtkGestureClick *g, int n, double x, double y, gpointer data) {
  (void)g; (void)n; (void)x; (void)y;
  ((App *)data)->seeking = TRUE;
}
static void on_seek_released(GtkGestureClick *g, int n, double x, double y, gpointer data) {
  (void)g; (void)n; (void)x; (void)y;
  App *a = data;
  a->seeking = FALSE;
  gint64 pos = (gint64)gtk_range_get_value(GTK_RANGE(a->seek));
  DZSeek((long long)pos);
  mpris_emit_seeked(a, pos); /* discontinuous jump: tell MPRIS clients */
}
static gboolean on_seek_change(GtkRange *r, GtkScrollType s, double value, gpointer data) {
  (void)r; (void)s; (void)data;
  DZSeek((long long)value); /* live seek while dragging */
  return FALSE;
}
static void on_volume_changed(GtkRange *r, gpointer data) {
  App *a = data;
  DZSetVolume(gtk_range_get_value(r));
  mpris_notify_volume(a);
}

/* ---------------------------------------------------------------------------
 * search
 * ------------------------------------------------------------------------- */

static void on_search_activate(GtkSearchEntry *entry, gpointer data) {
  App *a = data;
  const char *q = gtk_editable_get_text(GTK_EDITABLE(entry));
  if (q && *q) {
    adw_navigation_page_set_title(a->content_page, "Search");
    load_async(a, LOAD_SEARCH, q);
  }
}

/* ---------------------------------------------------------------------------
 * 300 ms poll: scrubber position, transport icon, natural-finish auto-advance
 * ------------------------------------------------------------------------- */

static gboolean tick(gpointer data) {
  App *a = data;
  int state = DZState(); /* 0 stopped,1 loading,2 playing,3 paused,4 error */
  gtk_button_set_icon_name(
      a->play_btn, state == 2 ? "media-playback-pause-symbolic" : "media-playback-start-symbolic");

  gint64 pos = DZPositionMS();
  gint64 dur = DZDurationMS();
  if (dur > 0 && !a->seeking) {
    gtk_range_set_range(GTK_RANGE(a->seek), 0, (double)dur);
    gtk_range_set_value(GTK_RANGE(a->seek), (double)pos);
  }
  char *pt = ms_to_text(pos), *dt = ms_to_text(dur);
  gtk_label_set_label(a->pos_label, pt);
  gtk_label_set_label(a->dur_label, dt);
  g_free(pt); g_free(dt);

  /* show the actual output format (e.g. "FLAC · lossless") next to the artist */
  if (a->current_index >= 0) {
    DzTrack *ct = g_list_model_get_item(G_LIST_MODEL(a->track_store), a->current_index);
    if (ct) {
      char *fmt = DZFormat(); /* labeled, malloc'd */
      if (fmt && *fmt) {
        char *sub = g_strconcat(ct->artist, "   ·   ", fmt, NULL);
        gtk_label_set_label(a->np_subtitle, sub);
        g_free(sub);
      } else {
        gtk_label_set_label(a->np_subtitle, ct->artist);
      }
      if (fmt) DZFree(fmt);
      g_object_unref(ct);
    }
  }

  /* mirror the playback status onto the OS media controls whenever it flips */
  const char *st = state == 2 ? "Playing" : (state == 3 ? "Paused" : "Stopped");
  if (g_strcmp0(st, a->mpris_status) != 0) {
    g_free(a->mpris_status);
    a->mpris_status = g_strdup(st);
    mpris_notify_status(a, st);
  }

  int fin = DZFinishedCount(); /* monotonic, +1 when a track ends naturally */
  if (fin != a->last_finished) {
    a->last_finished = fin;
    play_relative(a, 1); /* auto-advance */
  }
  return G_SOURCE_CONTINUE;
}

/* ---------------------------------------------------------------------------
 * login
 * ------------------------------------------------------------------------- */

static void init_worker(GTask *task, gpointer src, gpointer data, GCancellable *c) {
  (void)src; (void)c;
  char *arl = data;
  g_task_return_boolean(task, DZInit(arl) == 1);
}
static void init_done(GObject *src, GAsyncResult *res, gpointer data) {
  (void)src; (void)data;
  if (g_task_propagate_boolean(G_TASK(res), NULL)) {
    toast(APP, "Connected to Deezer");
    DZSetQuality(APP->quality); /* apply persisted quality once logged in */
    load_playlists_async(APP);
    /* select Liked Songs (row 0) → triggers the favorites load */
    GtkListBoxRow *row = gtk_list_box_get_row_at_index(APP->sidebar, 0);
    gtk_list_box_select_row(APP->sidebar, row);
  } else {
    toast(APP, "Login failed — check your ARL");
  }
}

/* ---------------------------------------------------------------------------
 * About
 * ------------------------------------------------------------------------- */

static void on_about(GSimpleAction *action, GVariant *param, gpointer data) {
  (void)action; (void)param; (void)data;
  const char *comments = "An open source reimplementation of Deezer.";
#if ADW_CHECK_VERSION(1, 6, 0)
  AdwDialog *about = adw_about_dialog_new();
  adw_about_dialog_set_application_name(ADW_ABOUT_DIALOG(about), "OpenDeezer");
  adw_about_dialog_set_application_icon(ADW_ABOUT_DIALOG(about), "org.opendeezer.OpenDeezer");
  adw_about_dialog_set_developer_name(ADW_ABOUT_DIALOG(about), "Cycl0o0");
  adw_about_dialog_set_version(ADW_ABOUT_DIALOG(about), "0.2.0");
  adw_about_dialog_set_comments(ADW_ABOUT_DIALOG(about), comments);
  adw_about_dialog_set_license_type(ADW_ABOUT_DIALOG(about), GTK_LICENSE_AGPL_3_0);
  adw_about_dialog_set_copyright(ADW_ABOUT_DIALOG(about), "© Cycl0o0");
  adw_dialog_present(about, GTK_WIDGET(APP->win));
#else
  GtkWidget *about = g_object_new(
      ADW_TYPE_ABOUT_WINDOW,
      "application-name", "OpenDeezer",
      "application-icon", "org.opendeezer.OpenDeezer",
      "developer-name", "Cycl0o0",
      "version", "0.2.0",
      "comments", comments,
      "license-type", GTK_LICENSE_AGPL_3_0,
      "copyright", "© Cycl0o0",
      NULL);
  gtk_window_set_transient_for(GTK_WINDOW(about), GTK_WINDOW(APP->win));
  gtk_window_set_modal(GTK_WINDOW(about), TRUE);
  gtk_window_present(GTK_WINDOW(about));
#endif
}

static void on_quit(GSimpleAction *action, GVariant *param, gpointer data) {
  (void)action; (void)param;
  g_application_quit(G_APPLICATION(data));
}

/* ---------------------------------------------------------------------------
 * theme
 * ------------------------------------------------------------------------- */

static void load_css(void) {
  /* libadwaita >=1.6 reads the CSS custom properties; the @define-color block
   * is the pre-1.6 fallback. Both are harmless to the other parser. */
  static const char *css =
      ":root{"
      "  --accent-bg-color:" ACCENT ";"
      "  --accent-color:" ACCENT ";"
      "  --accent-fg-color:#ffffff;"
      "}\n"
      "@define-color accent_bg_color " ACCENT ";\n"
      "@define-color accent_color " ACCENT ";\n"
      "@define-color accent_fg_color #ffffff;\n"
      ".np-cover{border-radius:6px;}\n";
  GtkCssProvider *p = gtk_css_provider_new();
#if GTK_CHECK_VERSION(4, 12, 0)
  gtk_css_provider_load_from_string(p, css);
#else
  gtk_css_provider_load_from_data(p, css, -1);
#endif
  gtk_style_context_add_provider_for_display(
      gdk_display_get_default(), GTK_STYLE_PROVIDER(p), GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
  g_object_unref(p);
}

/* ---------------------------------------------------------------------------
 * now-playing bottom bar
 * ------------------------------------------------------------------------- */

static GtkButton *transport_button(const char *icon) {
  GtkWidget *b = gtk_button_new_from_icon_name(icon);
  gtk_widget_add_css_class(b, "circular");
  gtk_widget_add_css_class(b, "flat");
  return GTK_BUTTON(b);
}

static GtkWidget *build_now_playing(App *a) {
  GtkWidget *bar = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 12);
  gtk_widget_set_margin_start(bar, 12);
  gtk_widget_set_margin_end(bar, 12);
  gtk_widget_set_margin_top(bar, 8);
  gtk_widget_set_margin_bottom(bar, 8);

  /* cover */
  a->np_cover = GTK_PICTURE(gtk_picture_new());
  gtk_widget_set_size_request(GTK_WIDGET(a->np_cover), 48, 48);
  gtk_picture_set_content_fit(a->np_cover, GTK_CONTENT_FIT_COVER);
  gtk_widget_add_css_class(GTK_WIDGET(a->np_cover), "np-cover");
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->np_cover));

  /* title + subtitle */
  GtkWidget *titles = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  gtk_widget_set_valign(titles, GTK_ALIGN_CENTER);
  gtk_widget_set_size_request(titles, 180, -1);
  a->np_title = GTK_LABEL(gtk_label_new(""));
  a->np_subtitle = GTK_LABEL(gtk_label_new(""));
  for (GtkLabel *l = a->np_title; l; l = (l == a->np_title ? a->np_subtitle : NULL)) {
    gtk_label_set_xalign(l, 0.0);
    gtk_label_set_ellipsize(l, PANGO_ELLIPSIZE_END);
  }
  gtk_widget_add_css_class(GTK_WIDGET(a->np_title), "heading");
  gtk_widget_add_css_class(GTK_WIDGET(a->np_subtitle), "dim-label");
  gtk_box_append(GTK_BOX(titles), GTK_WIDGET(a->np_title));
  gtk_box_append(GTK_BOX(titles), GTK_WIDGET(a->np_subtitle));
  gtk_box_append(GTK_BOX(bar), titles);

  /* transport */
  a->prev_btn = transport_button("media-skip-backward-symbolic");
  a->play_btn = transport_button("media-playback-start-symbolic");
  a->next_btn = transport_button("media-skip-forward-symbolic");
  g_signal_connect(a->prev_btn, "clicked", G_CALLBACK(on_prev_clicked), a);
  g_signal_connect(a->play_btn, "clicked", G_CALLBACK(on_play_clicked), a);
  g_signal_connect(a->next_btn, "clicked", G_CALLBACK(on_next_clicked), a);
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->prev_btn));
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->play_btn));
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->next_btn));

  /* position · scrubber · duration */
  a->pos_label = GTK_LABEL(gtk_label_new("0:00"));
  a->dur_label = GTK_LABEL(gtk_label_new("0:00"));
  gtk_widget_add_css_class(GTK_WIDGET(a->pos_label), "numeric");
  gtk_widget_add_css_class(GTK_WIDGET(a->dur_label), "numeric");
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->pos_label));

  a->seek = GTK_SCALE(gtk_scale_new_with_range(GTK_ORIENTATION_HORIZONTAL, 0, 1, 1));
  gtk_scale_set_draw_value(a->seek, FALSE);
  gtk_widget_set_hexpand(GTK_WIDGET(a->seek), TRUE);
  gtk_widget_set_valign(GTK_WIDGET(a->seek), GTK_ALIGN_CENTER);
  g_signal_connect(a->seek, "change-value", G_CALLBACK(on_seek_change), a);
  GtkGesture *click = gtk_gesture_click_new();
  g_signal_connect(click, "pressed", G_CALLBACK(on_seek_pressed), a);
  g_signal_connect(click, "released", G_CALLBACK(on_seek_released), a);
  /* Capture phase runs before GtkScale's own drag gesture, so both pressed and
   * released always fire — otherwise a missed "released" leaves seeking stuck. */
  gtk_event_controller_set_propagation_phase(GTK_EVENT_CONTROLLER(click), GTK_PHASE_CAPTURE);
  gtk_widget_add_controller(GTK_WIDGET(a->seek), GTK_EVENT_CONTROLLER(click));
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->seek));
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->dur_label));

  /* volume */
  gtk_box_append(GTK_BOX(bar), gtk_image_new_from_icon_name("audio-volume-high-symbolic"));
  a->volume = GTK_SCALE(gtk_scale_new_with_range(GTK_ORIENTATION_HORIZONTAL, 0, 1, 0.01));
  gtk_scale_set_draw_value(a->volume, FALSE);
  gtk_range_set_value(GTK_RANGE(a->volume), DZVolume());
  gtk_widget_set_size_request(GTK_WIDGET(a->volume), 100, -1);
  gtk_widget_set_valign(GTK_WIDGET(a->volume), GTK_ALIGN_CENTER);
  g_signal_connect(a->volume, "value-changed", G_CALLBACK(on_volume_changed), a);
  gtk_box_append(GTK_BOX(bar), GTK_WIDGET(a->volume));

  return bar;
}

/* ---------------------------------------------------------------------------
 * window assembly
 * ------------------------------------------------------------------------- */

static GtkWidget *build_sidebar(App *a) {
  a->sidebar = GTK_LIST_BOX(gtk_list_box_new());
  gtk_list_box_set_selection_mode(a->sidebar, GTK_SELECTION_SINGLE);
  gtk_widget_add_css_class(GTK_WIDGET(a->sidebar), "navigation-sidebar");
  g_signal_connect(a->sidebar, "row-selected", G_CALLBACK(on_sidebar_selected), a);

  /* static Liked Songs entry; playlists are appended after login */
  gtk_list_box_append(a->sidebar,
      make_side_row("Liked Songs", "Your favorites", "emblem-favorite-symbolic", ROW_LIKED, ""));

  GtkWidget *scroll = gtk_scrolled_window_new();
  gtk_scrolled_window_set_child(GTK_SCROLLED_WINDOW(scroll), GTK_WIDGET(a->sidebar));
  gtk_widget_set_vexpand(scroll, TRUE);
  return scroll;
}

static GtkWidget *build_track_view(App *a) {
  a->track_store = g_list_store_new(DZ_TYPE_TRACK);
  a->track_sel = gtk_single_selection_new(G_LIST_MODEL(g_object_ref(a->track_store)));
  gtk_single_selection_set_autoselect(a->track_sel, FALSE);
  gtk_single_selection_set_can_unselect(a->track_sel, TRUE);

  a->track_view =
      GTK_COLUMN_VIEW(gtk_column_view_new(GTK_SELECTION_MODEL(g_object_ref(a->track_sel))));
  gtk_column_view_set_show_row_separators(a->track_view, TRUE);
  gtk_column_view_set_show_column_separators(a->track_view, FALSE);
  g_signal_connect(a->track_view, "activate", G_CALLBACK(on_row_activate), a);

  GtkColumnViewColumn *cols[] = {
      make_column("Title", TRUE, FALSE, G_CALLBACK(bind_title)),
      make_column("Artist", TRUE, FALSE, G_CALLBACK(bind_artist)),
      make_column("Album", TRUE, FALSE, G_CALLBACK(bind_album)),
      make_column("Time", FALSE, TRUE, G_CALLBACK(bind_time)),
  };
  for (guint i = 0; i < G_N_ELEMENTS(cols); i++) {
    gtk_column_view_append_column(a->track_view, cols[i]);
    g_object_unref(cols[i]);
  }

  GtkWidget *scroll = gtk_scrolled_window_new();
  gtk_scrolled_window_set_child(GTK_SCROLLED_WINDOW(scroll), GTK_WIDGET(a->track_view));
  gtk_widget_set_vexpand(scroll, TRUE);
  return scroll;
}

static void on_activate(GApplication *app, gpointer data) {
  (void)data;
  if (APP) { /* already built (re-activation): un-hide + raise the window */
    show_window(APP);
    return;
  }

  load_css();
  adw_style_manager_set_color_scheme(adw_style_manager_get_default(), ADW_COLOR_SCHEME_PREFER_DARK);

  /* make the embedded app icon resolvable by app-id (window/shell icon) */
  gtk_icon_theme_add_resource_path(
      gtk_icon_theme_get_for_display(gdk_display_get_default()),
      "/org/opendeezer/OpenDeezer/icons");

  App *a = g_new0(App, 1);
  a->app = ADW_APPLICATION(app);
  a->current_index = -1;
  APP = a;

  /* load persisted settings; quality is applied after login (init_done) */
  settings_load(a);

  /* publish ourselves on the session bus for the OS media controls */
  mpris_setup(a);

  a->win = ADW_APPLICATION_WINDOW(adw_application_window_new(GTK_APPLICATION(app)));
  gtk_window_set_title(GTK_WINDOW(a->win), "OpenDeezer");
  gtk_window_set_default_size(GTK_WINDOW(a->win), 1100, 720);
  /* honour close-to-tray / background playback */
  g_signal_connect(a->win, "close-request", G_CALLBACK(on_window_close), a);

  /* window actions + menu */
  GSimpleAction *about_act = g_simple_action_new("about", NULL);
  g_signal_connect(about_act, "activate", G_CALLBACK(on_about), NULL);
  g_action_map_add_action(G_ACTION_MAP(app), G_ACTION(about_act));
  g_object_unref(about_act);
  GSimpleAction *quit_act = g_simple_action_new("quit", NULL);
  g_signal_connect(quit_act, "activate", G_CALLBACK(on_quit), app);
  g_action_map_add_action(G_ACTION_MAP(app), G_ACTION(quit_act));
  g_object_unref(quit_act);
  GSimpleAction *settings_act = g_simple_action_new("settings", NULL);
  g_signal_connect(settings_act, "activate", G_CALLBACK(on_settings), NULL);
  g_action_map_add_action(G_ACTION_MAP(app), G_ACTION(settings_act));
  g_object_unref(settings_act);
  const char *settings_accels[] = {"<Ctrl>comma", NULL};
  gtk_application_set_accels_for_action(GTK_APPLICATION(app), "app.settings", settings_accels);

  GMenu *menu = g_menu_new();
  g_menu_append(menu, "Settings", "app.settings");
  g_menu_append(menu, "About OpenDeezer", "app.about");
  g_menu_append(menu, "Quit", "app.quit");

  /* ---- sidebar pane ---- */
  AdwToolbarView *side_tv = ADW_TOOLBAR_VIEW(adw_toolbar_view_new());
  GtkWidget *side_hb = adw_header_bar_new();
  adw_header_bar_set_title_widget(ADW_HEADER_BAR(side_hb), adw_window_title_new("OpenDeezer", NULL));
  GtkMenuButton *menu_btn = GTK_MENU_BUTTON(gtk_menu_button_new());
  gtk_menu_button_set_icon_name(menu_btn, "open-menu-symbolic");
  gtk_menu_button_set_menu_model(menu_btn, G_MENU_MODEL(menu));
  adw_header_bar_pack_end(ADW_HEADER_BAR(side_hb), GTK_WIDGET(menu_btn));
  adw_toolbar_view_add_top_bar(side_tv, side_hb);
  adw_toolbar_view_set_content(side_tv, build_sidebar(a));
  AdwNavigationPage *side_page =
      adw_navigation_page_new(GTK_WIDGET(side_tv), "Library");

  /* ---- content pane ---- */
  AdwToolbarView *content_tv = ADW_TOOLBAR_VIEW(adw_toolbar_view_new());
  GtkWidget *content_hb = adw_header_bar_new();
  GtkWidget *search = gtk_search_entry_new();
  gtk_widget_set_size_request(search, 280, -1);
  g_object_set(search, "placeholder-text", "Search Deezer", NULL);
  /* GtkSearchEntry::activate only exists on GTK >= 4.14; connect to the
   * delegate GtkText's activate instead so Enter works on older GTK too. */
  GtkText *search_text = GTK_TEXT(gtk_editable_get_delegate(GTK_EDITABLE(search)));
  g_signal_connect(search_text, "activate", G_CALLBACK(on_search_activate), a);
  adw_header_bar_set_title_widget(ADW_HEADER_BAR(content_hb), search);
  adw_toolbar_view_add_top_bar(content_tv, content_hb);
  adw_toolbar_view_set_content(content_tv, build_track_view(a));
  adw_toolbar_view_add_bottom_bar(content_tv, build_now_playing(a));

  a->toast = ADW_TOAST_OVERLAY(adw_toast_overlay_new());
  adw_toast_overlay_set_child(a->toast, GTK_WIDGET(content_tv));
  a->content_page = adw_navigation_page_new(GTK_WIDGET(a->toast), "Liked Songs");

  /* ---- split ---- */
  AdwNavigationSplitView *split = ADW_NAVIGATION_SPLIT_VIEW(adw_navigation_split_view_new());
  adw_navigation_split_view_set_sidebar(split, side_page);
  adw_navigation_split_view_set_content(split, a->content_page);
  adw_navigation_split_view_set_min_sidebar_width(split, 240);
  adw_application_window_set_content(a->win, GTK_WIDGET(split));

  gtk_window_present(GTK_WINDOW(a->win));

  /* start the poll loop and kick off login */
  g_timeout_add(300, tick, a);

  char *arl = read_arl();
  if (!arl) {
    toast(a, "No ARL — set $DEEZER_ARL or ~/.config/opendeezer/arl.txt");
  } else {
    GTask *t = g_task_new(NULL, NULL, init_done, NULL);
    g_task_set_task_data(t, arl, g_free); /* arl freed with the task */
    g_task_run_in_thread(t, init_worker);
    g_object_unref(t);
  }
}

int main(int argc, char **argv) {
  AdwApplication *app = adw_application_new("org.opendeezer.OpenDeezer", G_APPLICATION_DEFAULT_FLAGS);
  g_signal_connect(app, "activate", G_CALLBACK(on_activate), NULL);
  int status = g_application_run(G_APPLICATION(app), argc, argv);
  g_object_unref(app);
  return status;
}
