/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/Cycl0o0/OpenDeezer/corelib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 13 "deezercore.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void DZFree(char* s);
extern unsigned char* DZFetch(char* url, int* outLen);
extern void DZFreeBytes(unsigned char* p);
extern int DZInit(char* arl);
extern char* DZLastErrorJSON(void);
extern void DZSetQuality(int level);
extern int DZQuality(void);
extern int DZHighQuality(void);
extern char* DZFormat(void);
extern char* DZUserID(void);
extern char* DZFavoritesJSON(void);
extern char* DZPlaylistsJSON(void);
extern char* DZPlaylistTracksJSON(char* id);
extern char* DZAlbumTracksJSON(char* id);
extern char* DZSearchJSON(char* q);
extern int DZPlay(char* trackID, long long durationMS);
extern void DZPause(void);
extern void DZResume(void);
extern void DZTogglePause(void);
extern void DZStop(void);
extern void DZSeek(long long ms);
extern int DZState(void);
extern long long DZPositionMS(void);
extern long long DZDurationMS(void);
extern void DZSetVolume(double v);
extern double DZVolume(void);
extern int DZFinishedCount(void);
extern void DZWebRemoteSetEnabled(int on);
extern char* DZWebRemoteInfoJSON(void);
extern unsigned char* DZWebRemoteQRPNG(int* outLen);

#ifdef __cplusplus
}
#endif
